### ISSUE TITLE
Crash due to missing folder path

### ISSUE THREAD

**Issue by Mithil467** [kriticalflare/KustomPyper#1]
Clicking next button crashes the app

 - Windows 10
 - Python 3.7.4
 - KustomPyper source master https://github.com/kriticalflare/KustomPyper/commit/2abb22d262538c53c75ffd65612c3e9fb3d81b32

**To Reproduce**
1. Run python app.py
2. Click on next wallpaper button
3. See error

**Expected behavior**
Expected behavior is that the app shouldn't crash.
But it does.

Traceback output:

```
Traceback (most recent call last):
  File "app.py", line 76, in run
    self.reddit_instance.downloadWall()
  File "C:\Projects\KustomPyper\reddit.py", line 65, in downloadWall
    with open(self.download_path, 'wb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aakanksha\\AppData\\Local\\Programs\\KustomPyper\\pic1.jpg'
```
This issue is happening because open() function doesn't create folders if they are missing.

**Comment by kriticalflare** [comment]
Thanks for your interest in the project and the PR!
