### ISSUE TITLE
[Feature] Could you please tell me what's the "reddit_client_id" and the '<client-secret>'?

### ISSUE THREAD

**Issue by FVDH1127** [kriticalflare/KustomPyper#9]
Could you please tell me what's the "reddit_client_id" and the '<client-secret>'?

**Comment by kriticalflare** [comment]
Those are the api keys that you will need to create for the reddit features in the KustomPyper. You can refer https://www.geeksforgeeks.org/how-to-get-client_id-and-client_secret-for-python-reddit-api-registration/ if you want a step by step demonstration of creating your own keys
